name: Build Multi-Architecture

on:
  push:
    branches:
      - main

jobs:
  dist:
    name: Dist
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Export Musl Binaries
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.musl
          platforms: linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le
          outputs: type=local,dest=./dist

      - name: Prepare Release Binaries
        run: |
          mkdir -p release
          cp dist/linux_amd64/fusequota_musl release/fusequota-x86_64
          cp dist/linux_arm64/fusequota_musl release/fusequota-aarch64
          cp dist/linux_riscv64/fusequota_musl release/fusequota-riscv64
          cp dist/linux_ppc64le/fusequota_musl release/fusequota-ppc64le
          chmod +x release/*

      - name: Get tag or commit id
        id: get-version-id
        uses: iawia002/get-tag-or-commit-id@v1

      - name: Create Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/*
          file_glob: true
          tag: ${{ steps.get-version-id.outputs.id }}
          overwrite: true
